log_level: debug
branch-protection:
  protect: true
  orgs:
    jenkins-x-charts:
      required_status_checks:
        contexts: ["tekton"]
    jenkins-x-apps:
      required_status_checks:
        contexts: ["tekton"]
    jenkins-x:
      repos:
        jx:
          required_status_checks:
            contexts:
              ["bdd","integration","lint"]
        jenkins-x-builders:
          required_status_checks:
            contexts: ["tekton"]
        jenkins-x-serverless:
          required_status_checks:
            contexts: ["tekton"]
        jenkins-x-serverless-filerunner:
          required_status_checks:
            contexts: ["tekton"]
        jenkins-x-builders-base:
          required_status_checks:
            contexts: ["tekton"]
        jenkins-x-builders-base-image:
          required_status_checks:
            contexts: ["tekton"]
        dev-env:
          required_status_checks:
            contexts: ["tekton"]
        updatebot:
          required_status_checks:
            contexts: ["tekton"]
        ext-java-code-quality:
          required_status_checks:
            contexts: ["tekton"]
        jx-tutorial:
          required_status_checks:
            contexts: ["tekton"]
        homebrew-jx:
          required_status_checks:
            contexts: ["tekton"]
    cb-kubecd:
      required_status_checks:
        contexts: ["tekton"]
owners_dir_blacklist:
  default: null
  repos: null
prowjob_namespace: jx
pod_namespace: jx
push_gateway: {}
sinker:
  resync_period: 5m
  max_prowjob_age: 4h
  max_pod_age: 4h
periodics:
postsubmits:
  jenkins-x/jenkins-x-serverless:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x/jenkins-x-serverless-filerunner:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x/dev-env:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x/updatebot:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x/ext-java-code-quality:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x-charts/hey:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x-charts/nexus:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x-charts/prow:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x-charts/tekton:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x-charts/environment-controller:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x-charts/openshift-namespace-rbac-chart:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x-charts/athens-proxy:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x-charts/vault-operator:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x-charts/knative-build:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x-charts/jx-build-templates:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x/jenkins-x-builders:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x/jenkins-x-builders-base:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x/jenkins-x-builders-base-image:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x/jx:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x/jx-tutorial:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x/homebrew-jx:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x-apps/jx-app-sonarqube:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x-apps/jx-app-grafana:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x-apps/jx-app-cheese:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x-apps/jx-app-istio:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x-apps/jx-app-gitea:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x-apps/jx-app-anchore:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x-apps/jx-app-jenkins:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x-apps/jx-app-ambassador:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
  jenkins-x-apps/jx-app-athens:
  - agent: tekton
    context: tekton
    name: tekton
    branches:
    - master
presubmits:
  jenkins-x/jenkins-x-versions:
  - agent: tekton
    always_run: false
    context: static
    name: static
    rerun_command: /test static
    trigger: (?m)^/test( all| this| static),?(s+|$)
  - agent: tekton
    always_run: false
    context: prow
    name: prow
    rerun_command: /test prow
    trigger: (?m)^/test( all| this| prow),?(s+|$)
  - agent: tekton
    always_run: false
    context: gitops
    name: gitops
    rerun_command: /test gitops
    trigger: (?m)^/test( all| gitops),?(s+|$)
  - agent: tekton
    always_run: false
    context: tekton
    name: tekton
    rerun_command: /test tekton
    trigger: (?m)^/test( all| tekton),?(s+|$)
  - agent: tekton
    always_run: false
    context: ng
    name: ng
    rerun_command: /test ng
    trigger: (?m)^/test( all| ng),?(s+|$)
  jenkins-x/jx:
  - agent: tekton
    always_run: true
    context: bdd
    name: bdd
    rerun_command: /test bdd
    trigger: (?m)^/test( all| bdd),?(s+|$)
  - agent: tekton
    always_run: true
    context: integration
    name: integration
    rerun_command: /test integration
    trigger: (?m)^/test( all| integration),?(s+|$)
  - agent: tekton
    always_run: true
    context: lint
    name: lint
    rerun_command: /test lint
    trigger: (?m)^/test( all| lint),?(s+|$)
  jenkins-x/jx-tutorial:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
  jenkins-x/homebrew-jx:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
  rawlingsj/jx:
  - agent: tekton
    always_run: false
    context: tekton
    name: tekton
    rerun_command: /test tekton
    trigger: (?m)^/test( all| tekton),?(s+|$)
  jenkins-x/dev-env:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test tekton
    trigger: (?m)^/test( all| tekton),?(s+|$)
  jenkins-x/updatebot:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test tekton
    trigger: (?m)^/test( all| tekton),?(s+|$)
  jenkins-x/jenkins-x-serverless:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
  jenkins-x/jenkins-x-serverless-filerunner:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
  jenkins-x/ext-java-code-quality:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
  jenkins-x-charts/hey:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
  jenkins-x-charts/nexus:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
  jenkins-x-charts/prow:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
  jenkins-x-charts/tekton:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
  jenkins-x-charts/environment-controller:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
  jenkins-x-charts/openshift-namespace-rbac-chart:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
  jenkins-x-charts/athens-proxy:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test this
    trigger: (?m)^/test(all| this),?(s+|$)
  jenkins-x-charts/knative-build:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
  jenkins-x-charts/vault-operator:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton  
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
  jenkins-x-charts/jx-build-templates:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
  jenkins-x/jenkins-x-builders:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
  jenkins-x/jenkins-x-builders-base:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
  jenkins-x/jenkins-x-builders-base-image:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
  jenkins-x-apps/jx-app-anchore:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
  jenkins-x-apps/jx-app-jenkins:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
  jenkins-x-apps/jx-app-gitea:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
  jenkins-x-apps/jx-app-istio:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
  jenkins-x-apps/jx-app-grafana:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
  jenkins-x-apps/jx-app-cheese:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
  jenkins-x-apps/jx-app-sonarqube:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
  jenkins-x-apps/jx-app-ambassador:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
  jenkins-x-apps/jx-app-athens:
  - agent: tekton
    always_run: true
    context: tekton
    name: tekton
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(s+|$)
tide:
  sync_period: 2m
  status_update_period: 1m
  context_options:
    from-branch-protection: true
    skip-unknown-contexts: false
  queries:
  - labels:
    - updatebot
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - needs-ok-to-test
    - needs-rebase
    repos:
    - jenkins-x/jenkins-x-serverless
    - jenkins-x/jenkins-x-serverless-filerunner
    - jenkins-x/jenkins-x-builders
    - jenkins-x/jenkins-x-builders-base
    - jenkins-x/jenkins-x-builders-base-image
    - jenkins-x-charts/hey
    - jenkins-x-charts/nexus
    - jenkins-x-charts/prow
    - jenkins-x-charts/tekton
    - jenkins-x-charts/environment-controller
    - jenkins-x-charts/openshift-namespace-rbac-chart
    - jenkins-x-charts/athens-proxy
    - jenkins-x-charts/vault-operator
    - jenkins-x-charts/knative-build
    - jenkins-x-charts/jx-build-templates
    - jenkins-x/jx
    - jenkins-x/jx-tutorial
    - jenkins-x/homebrew-jx
    - jenkins-x/dev-env
    - jenkins-x/updatebot
    - jenkins-x/ext-java-code-quality
    - jenkins-x-apps/jx-app-sonarqube
    - jenkins-x-apps/jx-app-cheese
    - jenkins-x-apps/jx-app-grafana
    - jenkins-x-apps/jx-app-istio
    - jenkins-x-apps/jx-app-gitea
    - jenkins-x-apps/jx-app-jenkins
    - jenkins-x-apps/jx-app-anchore
    - jenkins-x-apps/jx-app-ambassador
    - jenkins-x-apps/jx-app-athens
  - labels:
    - approved
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - needs-ok-to-test
    - needs-rebase
    repos:
    - jenkins-x/dummy
    - jenkins-x/jenkins-x-serverless
    - jenkins-x/jenkins-x-serverless-filerunner
    - jenkins-x/jenkins-x-builders
    - jenkins-x/jenkins-x-builders-base
    - jenkins-x/jenkins-x-builders-base-image
    - jenkins-x/jx-tutorial
    - jenkins-x/homebrew-jx
    - jenkins-x-charts/hey
    - jenkins-x-charts/nexus
    - jenkins-x-charts/prow
    - jenkins-x-charts/tekton
    - jenkins-x-charts/environment-controller
    - jenkins-x-charts/openshift-namespace-rbac-chart
    - jenkins-x-charts/athens-proxy
    - jenkins-x-charts/vault-operator
    - jenkins-x-charts/knative-build
    - jenkins-x-charts/jx-build-templates 
    - jenkins-x/dev-env
    - jenkins-x/updatebot
    - jenkins-x/ext-java-code-quality
    - jenkins-x-apps/jx-app-sonarqube
    - jenkins-x-apps/jx-app-cheese
    - jenkins-x-apps/jx-app-grafana
    - jenkins-x-apps/jx-app-istio
    - jenkins-x-apps/jx-app-gitea
    - jenkins-x-apps/jx-app-jenkins
    - jenkins-x-apps/jx-app-anchore
    - jenkins-x-apps/jx-app-ambassador
    - jenkins-x-apps/jx-app-athens
  - labels:
    - approved
    - lgtm
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - needs-ok-to-test
    - needs-rebase
    repos:
    - jenkins-x/jx
  target_url: https://core.jx.tekton.rawlings.it/foo
